FROM gcc:8.2.0 as builder

WORKDIR /src/remserial
COPY remserial-1.4 .
RUN make

FROM ubuntu:bionic-20181112
WORKDIR /root/
COPY --from=builder /src/remserial/remserial .
COPY run.sh .

ENV REMSERIAL_FLAGS=""
ENV REMSERIAL_DEVICE="/dev/remserial"

CMD ["./run.sh"]
